webtalk_init -webtalk_dir C:/Users/viannais/Google Drive/UERGS/2021_02_Organizacao_Computadores/Apresentação_Oficial/32-bitMips-master-float/miTo.sim/sim_3/behav/xsim/xsim.dir/testebenche_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul 23 21:07:35 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3173277" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "35bdc835-8a44-408c-a301-94318adb70c5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6b16120a2d824e05bcce677717a8d6fd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8500T CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7148_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1671134582 -regid "" -xml C:/Users/viannais/Google Drive/UERGS/2021_02_Organizacao_Computadores/Apresentação_Oficial/32-bitMips-master-float/miTo.sim/sim_3/behav/xsim/xsim.dir/testebenche_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/viannais/Google Drive/UERGS/2021_02_Organizacao_Computadores/Apresentação_Oficial/32-bitMips-master-float/miTo.sim/sim_3/behav/xsim/xsim.dir/testebenche_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/viannais/Google Drive/UERGS/2021_02_Organizacao_Computadores/Apresentação_Oficial/32-bitMips-master-float/miTo.sim/sim_3/behav/xsim/xsim.dir/testebenche_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
